config/routes.rb
Rails.application.routes.draw do
  root 'tempature#show'
  get 'temp', to: 'tempature#show'
  get 'get_csv', to: 'tempature#csv_temp'

  resources :heaters do
    resources :heater_statuses
    resources :heater_commands, only: [:show, :create, :new, :destroy]
  end

  namespace :api do
    namespace :v1 do
      resources :heaters, only: [:create, :show] do
        resources :heater_statuses, only: [:create]
        resources :heater_commands, only: [:show, :index, :update]
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/heater.rb
class Heater < ApplicationRecord
  has_many :heating_times, dependent: :destroy
  has_many :heater_statuses, dependent: :destroy
  has_many :heater_commands, dependent: :destroy
end

app/models/heater_command.rb
class HeaterCommand < ApplicationRecord
  STATUSES = ["SET_KEBAB","SET_HEATING_TIME","REMOVE_TIMED","STOP_HEATING","REMOVE_KEBAB"]
  belongs_to :heater
  after_initialize :init

  def self.status_list
    return STATUSES
  end

  private
   def init
     self.seen  ||= false
   end
end

app/models/heater_status.rb
class HeaterStatus < ApplicationRecord
  belongs_to :heater
end

app/models/tempature.rb
class Tempature < ApplicationRecord
  def self.to_csv(days)
    if /\A[0-9]+\z/.match(days) and not days.blank?
      days = days.to_i
    else
      days = 7
    end
    temp = Tempature.find_by_sql(
    ["Select * FROM tempatures WHERE created_at > ? ORDER BY created_at DESC LIMIT 10000", Time.now - days.days])
    csv = ""
    csv << "time,temp\n"
    temp.each do |temp|
      csv << temp.created_at.to_s(:dygraph) + "," + temp.temp.to_s + "\n"
    end
    return csv
  end


end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  protect_from_forgery with: :null_session

  before_action :destroy_session

  def destroy_session
    request.session_options[:skip] = true
  end
end

app/controllers/api/v1/heater_commands_controller.rb
class Api::V1::HeaterCommandsController < Api::V1::BaseController
  def index
    heater = Heater.find(params[:heater_id])
    commands = heater.heater_commands.where.not(seen: true)
    render json: commands, each_serializer: Api::V1::HeaterCommandSerializer
  end

  def update
    heater = Heater.find(params[:heater_id])
    command = heater.heater_commands.find(params[:id])
    if command.valid?
      command.update(command_params)
      head 200
    else
      head 409
    end
  end

  def show
    heater = Heater.find(params[:heater_id])
    commands = heater.heater_commands.find(params[:id])
    render(json: Api::V1::HeaterCommandSerializer.new(commands).to_json)
  end

  private
    def command_params
      params.permit(:seen)
    end
end

app/controllers/api/v1/heater_statuses_controller.rb
class Api::V1::HeaterStatusesController < Api::V1::BaseController

  def create
    heater = Heater.find(params[:heater_id])
    heater_status = heater.heater_statuses.new(heater_status_params)
    if heater_status.valid?
      heater_status.save
      head 201
    end
  end

  private
    def heater_status_params
      params.require(:heater_status).permit(:tempature, :last_seen, :status)
    end
end

app/controllers/api/v1/heaters_controller.rb
class Api::V1::HeatersController < Api::V1::BaseController
  def show
    heater = Heater.find(params[:id])

    render(json: Api::V1::HeaterSerializer.new(heater).to_json)
  end

  def create
    heater = Heater.new(heater_params)
    if heater.valid?
      heater.save
      head 201
    end
  end

  private
    def heater_params
      params.require(:heater).permit(:owner,:name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/heater_commands_controller.rb
class HeaterCommandsController < ApplicationController
  def show
    @commands = HeaterCommand.all
  end

  def new
    @heater = Heater.find(params[:heater_id])
    @command = HeaterCommand.new
  end

  def create
    @heater = Heater.find(params[:heater_id])
    @command = @heater.heater_commands.new(heater_command_params)
    if @command.valid?
      @command.save
      flash.now[:success] = "Lähetetty"
      redirect_to @heater
    else
      redirect_to heater_path(params[:heater_id])
    end
  end

  def destroy
    @heater = Heater.find(params[:heater_id])
    @command = @heater.heater_commands.find(params[:id])
    @command.destroy
    redirect_to heater_path(params[:heater_id])
  end

  private
    def heater_command_params
      params.require(:heater_command).permit(:seen, :command, :heating)
    end
end

app/controllers/heater_statuses_controller.rb
class HeaterStatusesController < ApplicationController
  def destroy
    @heater = Heater.find(params[:heater_id])
    @status = @heater.heater_statuses.find(params[:id])
    @status.destroy
    redirect_to heater_path(params[:heater_id])
  end
end

app/controllers/heaters_controller.rb
class HeatersController < ApplicationController
  def index
    @heaters = Heater.all
  end

  def new
    @heater = Heater.new
  end

  def show
    @heater = Heater.find(params[:id])
    @command = HeaterCommand.new
  end

  def create
    @heater = Heater.new(heater_params)
    if @heater.valid?
      @heater.save
      flash.now[:success] = "Lähetetty"
      redirect_to root_path
    else
      render :action => 'new'
    end
  end

  private
    def heater_params
      params.require(:heater).permit(:owner,:name)
    end

end

app/controllers/tempature_controller.rb
class TempatureController < ApplicationController
  def show
    @temp = Tempature.order("id").last
    @days = params[:days] ||= 7
  end

  def csv_temp
    temp = Tempature.to_csv(params[:days])
    render plain: temp
  end

  def new

  end

  def create
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/heater_command_helper.rb
module HeaterCommandHelper
end

app/helpers/heater_helper.rb
module HeaterHelper
end

app/helpers/tempature_helper.rb
module TempatureHelper
end

app/views/heater_commands/_show.html.erb
<h3> Komento log:</h3>
<table>
<tr>
  <th>
    Toimitettu
  </th>
  <th>
    Komento
  </th>
  <th>
    Lämmitysaika
  </th>
  <th>
    Luotu
  </th>
  <th>
    Toiminto
  </th>
</tr>
<% heater_command.order(created_at: :desc).each do |h| %>
  <tr>
    <td>
      <%= h.seen %>
    </td>
    <td>
      <%= h.command %></br>
    </td>
    <td>
      <%= h.heating %></br>
    </td>
    <td>
      <%= time_ago_in_words(h.created_at) %>
    </td>
    <td>
      <%= link_to 'Poista', heater_heater_command_path(@heater,h), method: :delete %>
    </td>
  </tr>
<% end %>
</table>

app/views/heater_commands/new.html.erb
<%= form_for [@heater, @command] do |f|%>
  <p>
    <%= f.label :command, "Komento" %>
    <%= f.collection_select :command, HeaterCommand.status_list, :to_s, :to_s, include_blank: false %>
  </p>
  <p>
    <%= f.label :heating, "Lämmitysaika" %>
    <%= f.text_field :heating %>
  </p>
  <%= f.submit "Lähetä"%>
<% end %>

app/views/heaters/new.html.erb
<%= form_for @heater, :method => :post do |f| %>
  <p>
    <%= f.label :owner %>
    <%= f.text_field :owner %>
  </p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  <p>
    <%= f.submit 'Luo uus' %>
  <% end %>

app/views/heaters/show.html.erb
  <%= @heater.owner %></br>
  <%= @heater.name %>
<h1>IoT-Autonpolttaja</h1>
<%= render template: "heater_commands/new", command: @heater.heater_commands %>

  <h3> Status log:</h3>
<table>
  <tr>
    <th>
      Lämpötila
    </th>
    <th>
      Viimeksi nähty
    </th>
    <th>
      status
    </th>
    <th>
      Luotu
    </th>
    <th>
      Toiminto
    </th>
  </tr>
  <% @heater.heater_statuses.order(created_at: :desc).each do |h| %>
    <tr>
      <td>
        <%= h.tempature %>
      </td>
      <td>
        <%= h.last_seen %></br>
      </td>
      <td>
        <%= h.status %></br>
      </td>
      <td>
        <%= time_ago_in_words(h.created_at) %>
      </td>
      <td>
        <%= link_to 'Poista', heater_heater_status_path(@heater,h), method: :delete %>
      </td>
    </tr>
  <% end %>
</table>

<%= render 'heater_commands/show', heater_command: @heater.heater_commands %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IotAutonpolttaja</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tempature/show.html.erb
<div id="graph" style="width: 60%"></div>
<script>
  new Dygraph(document.getElementById("graph"),
  "<%= get_csv_path(days: @days) %>",{
  rollPeriod: 10,
  title: "IoT-Autonpolttaja"
  })
</script>

<%= form_for temp_path, method: :get do |f| %>
  <%= f.label :days, "Päivät: " %>
  <%= text_field_tag :days, params[:days] %>
  <%= f.submit 'Päivitä', name: nil%>
<% end %>